services:
  postgres:
    image: postgres:16-alpine
    container_name: gastos-compartidos-db
    environment:
      POSTGRES_DB: gastos_compartidos
      POSTGRES_USER: gastos_user
      POSTGRES_PASSWORD: gastos_pass
    ports:
      - "5433:5432"
    volumes:
      - gastos_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gastos_user -d gastos_compartidos"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  gastos_pg_data: